import { useGraphStore } from '../lib/store';
import HeroSection from './HeroSection';
import ContentCollection from './ContentCollection';
import BentoGrid from './BentoGrid';

export default function PlannerLayout() {
    const { nodes } = useGraphStore();

    // Find Root Node (Discovery)
    // In our store, the first node is usually the root, or we filter by no parent (though we don't store parentId in ReactFlow data easily without edges).
    // For now, getting the first node or finding one with type 'template' is a safe bet.
    const rootNode = nodes.length > 0 ? nodes[0].data : null;

    if (!rootNode) {
        return (
            <div className="flex flex-col items-center justify-center h-full text-gray-400">
                <p>Start a new journey to begin.</p>
            </div>
        );
    }

    return (
        <div className="flex-1 w-full h-full overflow-y-auto bg-gray-50 scroll-smooth">
            {/* Hero Section */}
            <HeroSection node={rootNode} />

            {/* Main Content Area */}
            <div className="max-w-5xl mx-auto px-6 py-12 space-y-16">

                {/* Placeholder for Bento Grid */}
                {/* Bento Grid (Overview) */}
                <BentoGrid sections={rootNode.content?.sections} />

                {/* Collections (Highlights, Food, Stays) */}
                <div className="space-y-16">
                    {/* Render sections dynamically if they exist */}
                    {rootNode.content?.sections?.map((section: any) => (
                        <ContentCollection
                            key={section.id}
                            title={section.title}
                            items={section.items}
                        />
                    ))}

                    {/* Fallback Placeholders if no sections - e.g. old data */}
                    {(!rootNode.content?.sections || rootNode.content.sections.length === 0) && (
                        <div className="text-center py-12 text-gray-400">
                            <p>Generating curated collections... (or no data available)</p>
                        </div>
                    )}
                </div>

            </div>

            {/* Footer / End of Guide */}
            <div className="bg-white border-t border-gray-100 py-12 text-center text-gray-400 text-sm">
                Generated by TravelMapper AI
            </div>
        </div>
    );
}
